### ISSUE TITLE
Create a helper function to validate webhook payment responses

### ISSUE THREAD

**Issue by FredSoares** [chuva-io/sisp_payments_js#15]
# Description
Once a user has processed their payments, SISP will return a response about the payment process using our `webhook` as they request implementation in the official [documentation]( https://www.vinti4.cv/documentation.aspx?id=682).

- Create a function that should receive this response and validate if the response was processed successfully or not.
```js
/**
 * VALIDATE PAYMENT RESPONSE
 * @param {Object} responseBody - Required - The response body returned in the webhook by SISP.
 * 
 * @returns {Object} error - An error object if there is an error, otherwise `undefined`. 
 * @returns {Number} error.code - The error code.
 * @returns {String} error.description - Error debug description.
 */
validatePayment(responseBody)
```

- Create reusable `PaymentError` structure with `code` and `description` properties.

| Code: `string`  | Description: `string`               |
|-------|-----------------------------------------------|
| 001   | Payment processing error: Invalid fingerprint |
| 002   | Payment processing error: Cancelled by user   |
| 003   | Payment processing error: Processing error    |

# SISP Payment Validation Implementation Info

1. Success Message Type
If the payment was successfully processed, SISP will send us a success message type that we can access in responseBody.message Type, and this message can be one of the following types:
```js
    // SUCCESS RESPONSE CONSTANTS
    const successMessageTypes = ["8", "10", "M", "P"];
    if (successMessageTypes.includes(responseBody.messageType)) {
       // Validate fingerprint of the result
    } else {
        return ({ code: 003, message: 'Payment processing error: Processing error' });
    }
```

2. Success Message Type
Validate fingerprint of the result. </br> In addition to checking the `messageType` field, it is necessary to check if the FingerPrint received in the resultFingerPrint field is the same as expected, which is calculated according to the use of the function `GenerateFingerPrintResponseSuccessful` see the official [documentation]( https://www.vinti4.cv/documentation.aspx?id=682).
```js
    /*VALIDATE SUCCESS FINGERPRINT*/
    if(responseBody.resultFingerPrint === calculatedFingerPrint)
        // Handle Successful Payment
        return ({ code: 200, message: 'Payment processing successfully' });
    else
        // Handle Unsuccessful Payment: Invalid Response Finger Print	
        return ({ code: 001, message: 'Payment processing error: Invalid fingerprint' });
```

3. Unsuccessful payment
We can get unsuccessful payment if success message type doesn't include any of the type that was described in the point 1, or if the result Fingerprint is different from the calculated fingerprint as showed in point 2 and other error we can get is if the users cancel their payments as the example below:

```js
if(responseBody.UserCancelled === 'true') {
    // User canceled purchase requisition
    return ({ code: 002, message: 'Payment processing error: Cancelled by user' });
}
```

# Testing Requirements
- Ensure all criteria outlined in this ticket is tested.

# README
## Validate Payment Processing Status (convenience method)
Check whether or not a payment was processed successfully.
**Note:** This method is provided as a convenience. See the SISP documentation for the request structure.

### Usage
Pass the Webhook request body to `validatePayment`. Returns an error object containing `code` and `description` if there is an error, otherwise returns `undefined`.

```js
validatePayment(responseBody)
```

#### Possible Errors
| Code: `string`  | Description: `string`               |
|-------|-----------------------------------------------|
| 001   | Payment processing error: Invalid fingerprint |
| 002   | Payment processing error: Cancelled by user   |
| 003   | Payment processing error: Processing error    |

### Example

```js
 app.post("/webhook-handler", (request, response) => {
     const error = sisp.validatePayment(request.body);

     if(error === undefined) {
         // Payment processed successfully
     } 
     else {
         // Payment processing error
         console.log(error.code);
         console.log(error.description);
     }
 }
```

**Comment by FabyoSK** [comment]
This ticket seems good to me, I think the `paymentProcessedSuccessfully` is a useful function to preserve te integrity of the system

**Comment by lcsfort** [comment]
@FredSoares It looks good, just a typo in `Create a function that should receive this response and validate if the response was processed _**with**_ successfully or not.` I believe that `with` should be removed. Another thing is that I'm seeing a lot `the SISP` I think is just `SISP`

**Comment by savylopes** [comment]
@FredSoares It seems great for me, this will facilitate validation of the payment process and make it more trusty an maintainable

**Comment by trismegis7us** [comment]
@FredSoares document all of the specific errors that can occur. I think you can them in a table in the README.
