### ISSUE TITLE
Add required fields for 3DSecure

### ISSUE THREAD

**Issue by BrunoPiMA** [chuva-io/sisp_payments_js#40]
purchaseRequest attribute in the formData is missing for 3DSecure

**Comment by FabyoSK** [comment]
Thanks for letting us know, 
Please provide more information/resource/documentation about `purchaseRequest` attribute, so we can discuss about it

**Comment by BrunoPiMA** [comment]
Here is the [document](https://github.com/chuva-io/sisp_payments_js/files/9920777/Pagamento.Web.Especificacao.Servico.pdf) with all information required to send a request to the 3DSServer.
The informations about the purchaseRequest attribute are in point "2.2.1 Pedido de pagamento" of the document.

**Comment by lcsfort** [comment]
To be done

- [x] Add tests cases
- [x] Update the documentation
- [x] Add a new function to handle purchases on Sisp class
- [x] Deprecate the old function to handle purchases
